apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami
  namespace: default
spec:
  interval: 1h0m0s
  url: https://charts.bitnami.com/bitnami
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: redis
      version: '17.10.3'
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: default
      interval: 2m
  values:
    metrics:
      enabled: true
    replica:
      replicaCount: 0
